"""
Canada power generation and natural gas from Statistics Canada (no key):

  Table 25-10-0015-01  Electric power generation, monthly generation by type of electricity
      -> canada_power_generation_daily.xlsx (standard power layout, one row per MONTH, MWh)
         plus a "Provinces" sheet (total generation by province), a "Provinces fossil" sheet (monthly
         non-renewable combustible generation by province) and, from table 25-10-0084-01 (annual electricity
         generated by fuel), a "Fuel mix annual" sheet: the coal / gas / oil / other split of each province's
         fossil generation, which the North America master applies to the monthly provincial fossil totals
  Table 25-10-0086-01  Natural gas supply and disposition, monthly (successor of 25-10-0055, inactive
                       since Dec 2025)
      -> canada_gas.xlsx ("Supply and disposition": every item for Canada, million m3/day; inventories in
         million m3)
  Tables 25-10-0022-01 (installed generating capacity by type, annual) and 25-10-0023-01 (conventional
  thermal capacity by principal fuel, annual)
      -> canada_power_capacity.xlsx (standard capacity layout, sheet "Monthly", one row per YEAR, MW)

StatCan publishes each table as one CSV zip; there is no date-range
query, so each run first asks the WDS API for the table's latest month
(getCubeMetadata) and downloads only when it is newer than the saved data
(when one happens, every downloaded month replaces the saved one, since
StatCan revises recent months).

StatCan reports generation by type of plant (hydraulic, tidal, wind,
solar, nuclear, ...) and, for fuel-burning plants, by fuel group: it no
longer splits combustible generation by turbine type (those rows are zero
in recent months), so the standard columns are Hydro (hydraulic + tidal),
Wind, Solar, Nuclear, Fossil (non-renewable combustible fuels: coal, gas,
oil - not split by fuel monthly), Bioenergy (biomass), Other.

Usage: python3 CANADA_STATCAN.py [--power-out ...] [--gas-out ...]
"""
import argparse
import io
import os
import re
import sys
import time
import zipfile

import pandas as pd
import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)  # repo root, for xlsx_notes
import xlsx_notes  # noqa: E402

DEFAULT_DIR = os.path.join(ROOT, "output", "Data and Chart Outputs")
CSV_ZIP = "https://www150.statcan.gc.ca/n1/tbl/csv/{pid}-eng.zip"
METADATA = "https://www150.statcan.gc.ca/t1/wds/rest/getCubeMetadata"
POWER_TABLE = 25100015
FUEL_TABLE = 25100084   # annual electricity generated by fuel (thermal plants), by province
GAS_TABLE = 25100086
CAP_TYPE_TABLE = 25100022
CAP_FUEL_TABLE = 25100023
HISTORY_START = "2019-01-01"
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                         "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"}

def get(url, **kw):
    last = None
    for attempt in range(3):
        try:
            r = requests.get(url, headers=HEADERS, timeout=(10, 300), **kw)
            r.raise_for_status()
            return r
        except requests.RequestException as e:
            last = e
            print(f"    attempt {attempt + 1}/3 failed: {type(e).__name__}: {str(e)[:200]}", flush=True)
            time.sleep(10 * (attempt + 1))
    raise last


def latest_month(pid):
    """The table's last reference month per StatCan's WDS metadata (None if the call fails)."""
    try:
        r = requests.post(METADATA, json=[{"productId": pid}], headers=HEADERS, timeout=(10, 60))
        r.raise_for_status()
        obj = r.json()[0]["object"]
        end = pd.Timestamp(obj["cubeEndDate"]).to_period("M").to_timestamp()
        print(f"  table {pid}: '{obj.get('cubeTitleEn')}', {obj.get('cubeStartDate')} to {obj['cubeEndDate']}, "
              f"released {obj.get('releaseTime')}", flush=True)
        return end
    except Exception as e:  # noqa: BLE001 - just download then
        print(f"  table {pid}: metadata call failed ({type(e).__name__}: {str(e)[:200]})", flush=True)
        return None


def download(pid):
    """Whole table as a DataFrame (the CSV inside StatCan's zip), from HISTORY_START, values in base units."""
    url = CSV_ZIP.format(pid=pid)
    print(f"  downloading {url}", flush=True)
    z = zipfile.ZipFile(io.BytesIO(get(url).content))
    name = next(n for n in z.namelist() if n.endswith(".csv") and "MetaData" not in n)
    d = pd.read_csv(z.open(name), dtype=str, encoding="utf-8-sig")
    d["date"] = pd.to_datetime(d["REF_DATE"], errors="coerce")
    d = d[d["date"] >= HISTORY_START].copy()
    scale = pd.to_numeric(d.get("SCALAR_ID", "0"), errors="coerce").fillna(0)
    d["value"] = pd.to_numeric(d["VALUE"], errors="coerce") * (10.0 ** scale)
    dims = list(d.columns[d.columns.get_loc("DGUID") + 1:d.columns.get_loc("UOM")])
    print(f"  {len(d)} rows from {HISTORY_START}; dimensions {dims}; UOM {sorted(d['UOM'].dropna().unique())}",
          flush=True)
    for dim in dims:
        print(f"    {dim}: {sorted(d[dim].dropna().unique())}", flush=True)
    return d, dims


def load(path, sheet):
    try:
        d = pd.read_excel(path, sheet_name=sheet, index_col=0)
    except (FileNotFoundError, ValueError, KeyError, OSError):
        return pd.DataFrame()
    d.index = pd.to_datetime(pd.Index(d.index).astype(str), errors="coerce")
    return d[d.index.notna()].sort_index()


def merge(new, saved):
    """Downloaded months win (StatCan revises); saved months the download no longer covers are kept."""
    if saved.empty:
        return new
    return new.combine_first(saved)[list(new.columns) + [c for c in saved.columns if c not in new.columns]]


def needs_update(pid, saved, force):
    end = latest_month(pid)
    if force or saved.empty or end is None:
        return True
    if saved.index.max() >= end:
        print(f"  table {pid}: saved data already runs to {saved.index.max():%Y-%m} - no download", flush=True)
        return False
    return True


def power(d, dims):
    """Canada by type (non-combustible plants) plus StatCan's combustible-fuel totals. StatCan stopped splitting
    combustible generation by turbine type (combustion / steam / internal combustion are zero in recent months), so
    fuel-burning plants come from its 'non-renewable combustible fuels' (Fossil) and 'biomass' (Bioenergy) totals."""
    cls = next(c for c in dims if "class" in c.lower())
    typ = next(c for c in dims if "type" in c.lower())
    d = d[d[cls].str.contains("total all classes", case=False, na=False)]
    d = d[d["UOM"].str.contains("megawatt", case=False, na=False)]
    ca = d[d["GEO"] == "Canada"]
    row = lambda pat: ca[ca[typ].str.contains(pat, case=False, na=False, regex=True)].groupby("date")["value"].sum()  # noqa: E731
    out = pd.DataFrame({"Hydro": row(r"^hydraulic|^tidal"), "Wind": row(r"^wind"), "Solar": row(r"^solar$"),
                        "Nuclear": row(r"^nuclear")})
    bio, fossil, comb = row(r"from biomass"), row(r"non-renewable combustible"), row(r"from combustible fuels")
    out["Fossil"] = fossil if len(fossil) else comb - bio
    out["Fossil"] = out["Fossil"].fillna(comb.reindex(out.index) - bio.reindex(out.index).fillna(0))
    out["Bioenergy"] = bio
    out["Other"] = row(r"^other types")
    out = out.add_suffix("_MWh")
    out["Total_MWh"] = row(r"^total all types")
    out = out.dropna(how="all").round(0)
    out.index.name = "date"
    print(out.tail(3).to_string(), flush=True)
    prov = d[d[typ].str.match(r"total all types", case=False, na=False) & (d["GEO"] != "Canada")]
    prov = prov.pivot_table(index="date", columns="GEO", values="value", aggfunc="sum").round(0)
    prov = prov[prov.sum().sort_values(ascending=False).index].add_suffix("_MWh")
    prov.index.name = "date"
    pf = d[d[typ].str.contains("non-renewable combustible", case=False, na=False) & (d["GEO"] != "Canada")]
    pf = pf.pivot_table(index="date", columns="GEO", values="value", aggfunc="sum").round(0)
    pf = pf[[c for c in prov.columns.str.replace("_MWh", "") if c in pf.columns]].add_suffix("_MWh")
    pf.index.name = "date"
    return out, prov, pf


FUEL_GROUPS = {   # table 25-10-0084 'electricity generated' items -> fossil groups (leaf items, no double counting)
    "Coal": ["Total coal"],
    "Gas": ["Natural gas", "Other gaseous fuels"],
    "Oil": ["Total heavy fuel oil", "Light fuel oil", "Diesel", "Propane"],
    "Other fossil": ["Petroleum coke", "Other liquid fuels", "Other solid fuels", "Steam from waste heat"],
}


def fuel_annual(d, dims):
    """Annual electricity generated (MWh) by fossil fuel group and province, all classes of producer."""
    d = d[d["UOM"].str.contains("megawatt", case=False, na=False)]
    cls = next((c for c in dims if "naics" in c.lower() or "industry" in c.lower()), None)
    if cls:
        d = d[d[cls].str.contains("total all", case=False, na=False)]
    fuel = next(c for c in dims if "fuel" in c.lower())
    d = d[d[fuel].str.endswith(", electricity generated", na=False)].copy()
    d["item"] = d[fuel].str.replace(", electricity generated", "", regex=False)
    cols = {}
    for grp, items in FUEL_GROUPS.items():
        x = d[d["item"].isin(items)].pivot_table(index="date", columns="GEO", values="value", aggfunc="sum")
        for geo in x.columns:
            cols[f"{geo}|{grp}"] = x[geo]
    out = pd.DataFrame(cols).sort_index().round(0)
    out = out[sorted(out.columns, key=lambda c: (c.split("|")[0], list(FUEL_GROUPS).index(c.split("|")[1])))]
    out.index.name = "date"
    return out


STOCK = re.compile(r"inventory", re.I)   # stocks (end/start of month), not flows: not divided by days


def gas(d, dims):
    unit = next((c for c in dims if "unit" in c.lower()), None)
    items = [c for c in dims if c != unit]
    d = d[d["GEO"] == "Canada"]
    metric = d[unit] if unit else d["UOM"]
    d = d[metric.str.contains("metre", case=False, na=False)].copy()
    d["item"] = d[items].fillna("").agg(" | ".join, axis=1).str.strip(" |").str.replace(r"\s+", " ", regex=True)
    w = d.pivot_table(index="date", columns="item", values="value", aggfunc="sum")
    w = w[[c for c in d["item"].drop_duplicates() if c in w.columns]]   # StatCan's own item order
    flows = [c for c in w.columns if not STOCK.search(c) or "change" in c.lower()]
    out = w[flows].div(w.index.days_in_month, axis=0) / 1e6          # m3 per month -> million m3 per day
    out.columns = [f"{c} (mcm/d)" for c in flows]
    for c in w.columns:
        if c not in flows:
            out[f"{c} (mcm)"] = w[c] / 1e6                             # stock, million m3
    out = out.round(3)
    out.index.name = "Month"
    return out


# Principal fuel (table 25-10-0023) -> standard capacity column (first match wins)
FUEL_MAP = [(r"coal", "Coal"), (r"natural gas", "Gas"), (r"petroleum|oil|diesel|fuel oil", "Oil"),
            (r"wood|biomass|pulping|landfill|biogas|black liquor|waste", "Bioenergy"), (r".", "Other")]


def only_totals(d, dim):
    """Collapse a dimension to its 'Total ...' member when it has one (so members are not double counted)."""
    tot = d[dim].str.match(r"total", case=False, na=False)
    return d[tot] if tot.any() else d


def to_mw(d):
    kw = d["UOM"].str.contains("kilowatt", case=False, na=False)
    return d["value"].where(~kw, d["value"] / 1000.0)


def capacity(type_tab, fuel_tab):
    """Annual MW by standard fuel: non-thermal types from 25-10-0022, thermal split by principal fuel from
    25-10-0023 (if that table can't be used, thermal capacity goes to Other)."""
    d, dims = type_tab
    d = d[d["GEO"] == "Canada"].copy()
    d["mw"] = to_mw(d)
    typ = next(c for c in dims if "type" in c.lower())
    for dim in dims:
        if dim != typ:
            d = only_totals(d, dim)
    row = lambda pat: d[d[typ].str.contains(pat, case=False, na=False, regex=True)].groupby("date")["mw"].sum()  # noqa: E731
    out = pd.DataFrame({"Hydro": row(r"^hydraulic|^tidal"), "Wind": row(r"^wind"), "Solar": row(r"^solar"),
                        "Nuclear": row(r"^nuclear")})
    other_clean = row(r"^geothermal|^other non-combustible")   # geothermal and other non-thermal plants
    total = row(r"^total installed|^total all types")
    thermal = row(r"^total thermal") - out["Nuclear"].fillna(0)   # StatCan's 'Total thermal' includes nuclear steam
    if thermal.dropna().empty:
        thermal = total - out.sum(axis=1, min_count=1) - other_clean.reindex(total.index).fillna(0)
    try:
        f, fdims = fuel_tab
        f = f[f["GEO"] == "Canada"].copy()
        f["mw"] = to_mw(f)
        fuel = next(c for c in fdims if "fuel" in c.lower())
        for dim in fdims:
            if dim != fuel:
                f = only_totals(f, dim)
        f = f[~f[fuel].str.match(r"total", case=False, na=False)].copy()
        f["std"] = f[fuel].map(lambda t: next(col for pat, col in FUEL_MAP if re.search(pat, t, re.I)))
        for t, c in sorted(set(zip(f[fuel], f["std"]))):
            print(f"    {t!r} -> {c}", flush=True)
        byfuel = f.pivot_table(index="date", columns="std", values="mw", aggfunc="sum")
        for c in byfuel.columns:
            out[c] = byfuel[c]
        # thermal capacity table 23 doesn't cover (e.g. a fuel the type table counts but table 23 omits) -> Other
        gap = (thermal - byfuel.sum(axis=1).reindex(thermal.index)).clip(lower=0)
        out["Other"] = (out["Other"].fillna(0) if "Other" in out else 0) + gap.where(gap > 1, 0)
    except Exception as e:  # noqa: BLE001
        print(f"  thermal-by-fuel table not usable ({type(e).__name__}: {e}); thermal capacity -> Other", flush=True)
        out["Other"] = thermal
    out["Other"] = out["Other"].fillna(0) + other_clean.reindex(out.index).fillna(0)
    out = out.reindex(columns=[c for c in ("Hydro", "Gas", "Wind", "Solar", "Coal", "Nuclear", "Oil", "Bioenergy",
                                            "Other") if c in out.columns]).add_suffix("_MW")
    out["Total_MW"] = total
    out = out.dropna(how="all").round(1)
    out.index.name = "date"
    print(out.tail(3).to_string(), flush=True)
    return out


def save(path, sheets, notes):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    xlsx_notes.write_workbook(path, sheets, notes, {"UNITS", "COVERAGE", "SOURCE"})
    print(f"Saved {path}: " + ", ".join(f"{k} {len(v)} rows" for k, v in sheets.items()), flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--power-out", default=os.path.join(DEFAULT_DIR, "canada_power_generation_daily.xlsx"))
    ap.add_argument("--gas-out", default=os.path.join(DEFAULT_DIR, "canada_gas.xlsx"))
    ap.add_argument("--capacity-out", default=os.path.join(DEFAULT_DIR, "canada_power_capacity.xlsx"))
    ap.add_argument("--force", action="store_true", help="download even if the saved data look current")
    args = ap.parse_args()
    ok = 0

    print("Power generation (table 25-10-0015-01)", flush=True)
    saved, saved_prov = load(args.power_out, "Daily"), load(args.power_out, "Provinces")
    saved_pf, saved_fuel = load(args.power_out, "Provinces fossil"), load(args.power_out, "Fuel mix annual")
    try:
        changed = False
        if needs_update(POWER_TABLE, saved, args.force) or saved_pf.empty:
            changed = True
            out, prov, pf = power(*download(POWER_TABLE))
            saved = saved[[c for c in saved.columns if c in out.columns]]   # columns retired by a layout change go
            out, prov, pf = merge(out, saved), merge(prov, saved_prov), merge(pf, saved_pf)
        else:
            out, prov, pf = saved, saved_prov, saved_pf
        fuel = saved_fuel
        try:
            if needs_update(FUEL_TABLE, saved_fuel, args.force):
                fuel = merge(fuel_annual(*download(FUEL_TABLE)), saved_fuel)
                changed = True
        except Exception as e:  # noqa: BLE001 - the fuel split is optional
            print(f"  fuel table {FUEL_TABLE} failed: {type(e).__name__}: {e}", flush=True)
        if changed:
            notes = [
                "UNITS",
                "MWh per MONTH (this standard 'Daily' layout holds one row per month, dated the 1st). "
                "Provinces: total generation by province, MWh per month. Provinces fossil: StatCan 'non-renewable "
                "combustible fuels' generation by province, MWh per month. Fuel mix annual: MWh per YEAR (dated 1 "
                "January) of fossil generation by fuel group and province, '<province>|<group>' columns (Coal; Gas = "
                "natural gas + other gaseous fuels; Oil = fuel oils, diesel, propane; Other fossil = petroleum coke, "
                "other liquid and solid fuels, steam from waste heat), table 25-10-0084-01, all classes of producer.",
                "Columns: Hydro = hydraulic + tidal turbines; Wind, Solar, Nuclear as named; Fossil = StatCan's "
                "'Total electricity production from non-renewable combustible fuels' (coal, natural gas, oil - not "
                "split by fuel monthly; the master splits it by province with the Fuel mix annual shares); "
                "Bioenergy = 'from biomass'; Other = 'Other types'; Total_MWh = 'Total all types'.",
                "Class of producer: total all classes (utilities and industry).",
                "",
                "COVERAGE",
                f"Canada, monthly, {out.index.min():%b %Y} to {out.index.max():%b %Y}. StatCan publishes about "
                "two to three months after the month ends. Fuel mix annual: " +
                (f"{fuel.index.min():%Y} to {fuel.index.max():%Y} (published about a year late)." if not fuel.empty
                 else "not available yet."),
                "",
                "SOURCE",
                "Statistics Canada, Table 25-10-0015-01 Electric power generation, monthly generation by type of "
                "electricity: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510001501 ; Table 25-10-0084-01 "
                "Electric power generation, fuel consumed and cost of fuel by electricity generating thermal plants: "
                "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510008401",
            ]
            sheets = {"Daily": out, "Provinces": prov, "Provinces fossil": pf}
            if not fuel.empty:
                sheets["Fuel mix annual"] = fuel
            save(args.power_out, sheets, notes)
        ok += 1
    except Exception as e:  # noqa: BLE001 - still try the gas table
        print(f"POWER FAILED: {type(e).__name__}: {e}", flush=True)

    print("Natural gas (table 25-10-0086-01)", flush=True)
    saved = load(args.gas_out, "Supply and disposition")
    try:
        if needs_update(GAS_TABLE, saved, args.force):
            new = gas(*download(GAS_TABLE))
            new.index = pd.to_datetime(new.index)
            out = merge(new, saved)
            out.index = out.index.strftime("%Y-%m")
            out.index.name = "Month"
            notes = [
                "UNITS",
                "Million cubic metres per day (mcm/d), monthly average = StatCan monthly volume / days in month. "
                "One column per StatCan item, Canada total, in StatCan's order. Inventories (stocks) are in million "
                "cubic metres (mcm), not per day.",
                "",
                "COVERAGE",
                f"Canada, monthly, {out.index.min()} to {out.index.max()}. StatCan publishes about "
                "two to three months after the month ends.",
                "",
                "SOURCE",
                "Statistics Canada, Table 25-10-0086-01 Natural gas supply and disposition, monthly: "
                "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510008601 (successor of table "
                "25-10-0055-01, inactive since December 2025).",
            ]
            save(args.gas_out, {"Supply and disposition": out}, notes)
        ok += 1
    except Exception as e:  # noqa: BLE001
        print(f"GAS FAILED: {type(e).__name__}: {e}", flush=True)
    print("Generating capacity (tables 25-10-0022-01, 25-10-0023-01)", flush=True)
    saved = load(args.capacity_out, "Monthly")
    try:
        if needs_update(CAP_TYPE_TABLE, saved, args.force):
            try:
                fuel_tab = download(CAP_FUEL_TABLE)
            except Exception as e:  # noqa: BLE001 - capacity() falls back to thermal -> Other
                print(f"  table {CAP_FUEL_TABLE} download failed: {e}", flush=True)
                fuel_tab = None
            out = capacity(download(CAP_TYPE_TABLE), fuel_tab)
            out = merge(out, saved[[c for c in saved.columns if c in out.columns]])
            notes = [
                "UNITS",
                "Installed generating capacity, MW, one row per YEAR (dated 1 January; StatCan's year-end figure).",
                "Hydro (hydraulic + tidal), Wind, Solar, Nuclear: table 25-10-0022 by type of generation. Coal, "
                "Gas, Oil: conventional thermal capacity by principal fuel, table 25-10-0023; Other = 'Other "
                "principal fuels' (biomass and other fuels - StatCan does not split them) plus geothermal and other "
                "non-combustible plants. Total_MW = 25-10-0022 'Total installed capacity'. All classes of producer "
                "(utilities and industry).",
                "",
                "COVERAGE",
                f"Canada, annual, {out.index.min():%Y} to {out.index.max():%Y}. StatCan publishes these tables about "
                "a year after the year ends; the dashboard carries the latest year forward.",
                "",
                "SOURCE",
                "Statistics Canada, Table 25-10-0022-01 Installed plants, annual generating capacity by type of "
                "electricity generation: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510002201 ; Table "
                "25-10-0023-01 Conventional thermal, annual generating capacity by class of electricity producer "
                "and principal fuel: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510002301",
            ]
            save(args.capacity_out, {"Monthly": out}, notes)
        ok += 1
    except Exception as e:  # noqa: BLE001
        print(f"CAPACITY FAILED: {type(e).__name__}: {e}", flush=True)
    if not ok:
        raise SystemExit("No StatCan table could be updated")


if __name__ == "__main__":
    main()
