"""
Sarawak Energy: annual net energy generated by plant and by fuel, from the company's own Annual and Sustainability
Reports (ASR). Sarawak (about 20% of Malaysia's demand) is not in GSO's Peninsular data, and Sarawak Energy publishes no
daily or monthly generation, so the annual report is the only sourced series (third-party assured tables).

Output: output/Data and Chart Outputs/sarawak_energy_annual.xlsx
  Annual by fuel  main-grid net generation by fuel (GWh) 2015-, plus northern and stand-alone grids and the all-grid total
  By plant        net energy generated by plant (GWh), with grid and fuel
  Capacity        available capacity (MW) and commissioning year by plant, as listed in the latest report
  Sources         report, URL, size, years taken from it

Sources (Sarawak Energy website; the pages time out from GitHub Actions but the report PDFs download):
  SEASR2019   2015-2019   https://www.sarawakenergy.com/assets/pdf/SEASR-2019.pdf
  ASR2024     2020-2024   https://www.sarawakenergy.com/assets/pdf/Sarawak-Energy-ASR2024.pdf
  ASR2025     tried every run (same URL pattern); if it exists its five years replace the older figures (restatements).
Incremental: the PDFs are only re-read when a source's size changed or a new report appears (sizes kept on 'Sources').
Basis: 'net energy generated' in MWh per plant from the 'Net Energy Generated' performance-data table of each report;
the headline generation mix (e.g. 34,444 GWh in 2024) is the Main Grid. Annual only; no monthly or daily data exists.

Usage: python3 asia/SARAWAK_ENERGY_ASR.py [--out PATH] [--from-text FILE.txt ...]   (--from-text parses saved page text)
"""
import argparse
import io
import os
import re
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root, for xlsx_notes

import xlsx_notes  # noqa: E402

BASE = "https://www.sarawakenergy.com/assets/pdf/"
SOURCES = [
    ("SEASR2019", BASE + "SEASR-2019.pdf", "Sarawak Energy Annual and Sustainability Report 2019"),
    ("ASR2024", BASE + "Sarawak-Energy-ASR2024.pdf", "Sarawak Energy Annual and Sustainability Report 2024"),
]
NEXT_YEAR = 2025  # tried every run: Sarawak-Energy-ASR{year}.pdf
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output",
                           "Data and Chart Outputs", "sarawak_energy_annual.xlsx")

# plant -> (grid, fuel); names as printed in the reports
PLANTS = {
    "Batang Ai": ("Main", "Hydro"), "Bakun": ("Main", "Hydro"), "Murum": ("Main", "Hydro"), "Lundu PS": ("Main", "Hydro"),
    "Sejingkat Power Corp.": ("Main", "Coal"), "PPLS Power Generation": ("Main", "Coal"),
    "Mukah Power Generation": ("Main", "Coal"), "Mukah Power Sdn. Bhd.": ("Main", "Coal"),
    "Balingian Power Generation": ("Main", "Coal"),
    "Sarawak Power Generation": ("Main", "Natural gas"), "Kidurong Power Generation 1": ("Main", "Natural gas"),
    "Kidurong Power Generation 2": ("Main", "Natural gas"), "Bintulu PS": ("Main", "Natural gas"),
    "Miri PS": ("Main", "Natural gas"), "Sg Biawak PS": ("Main", "Diesel"),
    "Lawas M/H (Kalamuku)": ("Northern", "Mini hydro"), "Lawas M/H (Sg.Kota 1)": ("Northern", "Mini hydro"),
    "Lawas M/H (Sg.Kota 2)": ("Northern", "Mini hydro"), "Limbang PS": ("Northern", "Diesel"),
    "Lawas PS": ("Northern", "Diesel"),
    "Belaga PS": ("Stand-alone", "Diesel"), "Ng Jagau PS": ("Stand-alone", "Diesel"),
    "Ng Entawau PS": ("Stand-alone", "Diesel"), "Mulu PS": ("Stand-alone", "Diesel"),
    "Long Lama PS": ("Stand-alone", "Diesel"), "Banting PS": ("Stand-alone", "Diesel"),
    "Paloh PS": ("Stand-alone", "Diesel"), "Kapit PS": ("Stand-alone", "Diesel"), "Song PS": ("Stand-alone", "Diesel"),
    "Ng Mujong PS": ("Stand-alone", "Diesel"), "Ng Ngungun PS": ("Stand-alone", "Diesel"),
    "Kg Bruit PS": ("Stand-alone", "Diesel"), "Kg Saai PS": ("Stand-alone", "Diesel"),
    "Bakun - Sg Asap PS": ("Stand-alone", "Diesel"),
}
# the same plant under its 2019-report name
ALIAS = {"Mukah Power Sdn. Bhd.": "Mukah Power Generation"}
NAMES = sorted(PLANTS, key=len, reverse=True)
LEAD = re.compile(r"^(?:Coal|Hydropower|Diesel-Standby|Diesel|BTU-Combined Cycle|BTU-Open Cycle|Miri-Open Cycle)\s+")
NUM = re.compile(r"^-?\d{1,3}(?:,\d{3})*\.\d{2}")
YEARS = re.compile(r"\b(20[12]\d)\b")
CAP = re.compile(r"^\s*(.+?)\s+([\d,.]+)\s?MW\s+(\d{4})\s*$")


def split_pages(text):
    """Saved probe text ('===== NAME page N =====') -> list of page texts; or one block."""
    parts = re.split(r"\n===== \S+ page \d+ =====\n", "\n" + text)
    return [p for p in parts if p.strip()]


def parse_values(rest, n):
    """Tokens after 'MWh': numbers (footnote digits glued on or standing alone are ignored) and '-' for not operating."""
    out = []
    for tok in rest.split():
        if tok == "-":
            out.append(None)
        elif NUM.match(tok):
            out.append(float(NUM.match(tok).group(0).replace(",", "")))
    if len(out) != n:
        raise ValueError(f"expected {n} values, got {len(out)} in {rest!r}")
    return out


def _merge_wrapped(lines):
    """Join plant names the PDF wrapped onto two lines ('... Sarawak Power' / 'Generation 1,026,084.62 ...')."""
    out, i = [], 0
    while i < len(lines):
        ln = lines[i]
        if i + 1 < len(lines) and lines[i + 1].startswith("Generation") and not re.search(r"\d,\d{3}", ln) and ln.endswith("Power"):
            ln = ln + " " + lines[i + 1]
            i += 1
            if i + 1 < len(lines) and not re.search(r"[A-Za-z]", lines[i + 1]) and re.search(r"\d", lines[i + 1]):
                ln = ln + " " + lines[i + 1]
                i += 1
        out.append(ln)
        i += 1
    return out


def parse_generation(pages):
    """-> {plant: {year: MWh}} and {(plants...): {year: reported total MWh}} from net-energy-generated tables."""
    gen, totals = {}, {}
    for pg in pages:
        years = None
        members = []
        lines = _merge_wrapped([ln.strip() for ln in pg.splitlines()])
        for ln in lines:
            ys = YEARS.findall(ln)
            if len(ys) == 5 and ("Unit" in ln or "Plant" in ln or "POWER STATION" in ln or "Disclosure" in ln):
                years = [int(y) for y in ys]
                members = []
                continue
            if "Availability Factor" in ln or "Equivalent Availability" in ln:
                years = None
            if years is None:
                continue
            if "Plant Type" in ln or "Total Net Energy Generated" in ln:
                members = []
            body = LEAD.sub("", re.sub(r"^.*?S2-33\(a\)", "", ln)).replace("Bakun - Sg Asap PS", "Bakun~Sg Asap PS")
            # 'Name MWh v1 .. v5' (2020+ reports) or 'Name v1 .. v5' (2019 report)
            m = re.match(r"^(.*?)\s+MWh\s+(.*)$", body) or re.match(r"^(\D*?)\s+(-\s.*|-$|\d{1,3}(?:,\d{3})*\.\d{2}.*)$", body)
            if not m:
                continue
            cand, rest = m.group(1).strip().replace("Bakun~Sg Asap PS", "Bakun - Sg Asap PS"), m.group(2)
            if cand == "Total":
                if members:
                    totals[tuple(sorted(set(members)))] = dict(zip(years, parse_values(rest, 5)))
                members = []
                continue
            name = next((nm for nm in NAMES if cand == nm), None)
            if not name:
                continue
            key = ALIAS.get(name, name)
            gen.setdefault(key, {})
            for y, v in zip(years, parse_values(rest, 5)):
                if v is not None:
                    gen[key][y] = v
            members.append(key)
    return gen, totals


def parse_capacity(pages):
    """Plant, available capacity (MW), commissioning year, fuel from the 'Available Capacity' lists of the report."""
    rows = []
    fuel = None
    for pg in pages:
        for ln in pg.splitlines():
            s = ln.strip()
            if s in ("Natural Gas", "Coal"):
                fuel = s
            m = CAP.match(ln)
            if m and "MW" in ln and len(m.group(1)) < 70:
                name = m.group(1).strip()
                f = "Hydro" if re.search(r"HEP|Hydro", name) else {"Natural Gas": "Natural gas"}.get(fuel, fuel)
                rows.append({"Plant": name, "Fuel": f or "", "Available capacity (MW)": float(m.group(2).replace(",", "")),
                             "Commissioned": int(m.group(3))})
    return pd.DataFrame(rows).drop_duplicates("Plant")


def check_totals(gen, totals):
    """Each reported 'Total' line must equal the sum of the plants listed above it (to 0.01% or 5 MWh)."""
    bad = []
    for members, tot in totals.items():
        for y, t in tot.items():
            s = sum(gen[p].get(y, 0.0) for p in members)
            if abs(s - t) > max(5.0, 1e-4 * abs(t)):
                bad.append((members, y, round(s, 2), t))
    if bad:
        raise SystemExit(f"plant sums do not match the reported totals: {bad[:5]}")
    return len(totals)


def build_tables(gen):
    years = sorted({y for d in gen.values() for y in d})
    rows = []
    for p, d in gen.items():
        g, f = PLANTS[p]
        rows.append({"Plant": p, "Grid": g, "Fuel": f, **{y: (d[y] / 1000 if y in d else None) for y in years}})
    by_plant = pd.DataFrame(rows).sort_values(["Grid", "Fuel", "Plant"], key=lambda s: s.map(
        {"Main": 0, "Northern": 1, "Stand-alone": 2, "Hydro": 0, "Coal": 1, "Natural gas": 2, "Mini hydro": 3, "Diesel": 4}).fillna(s))
    by_plant = by_plant.set_index("Plant")
    ann = pd.DataFrame(index=pd.Index(years, name="year"))
    main = by_plant[by_plant.Grid == "Main"]
    for fuel in ("Hydro", "Coal", "Natural gas", "Diesel"):
        ann[f"{fuel} (GWh)"] = main[main.Fuel == fuel][years].sum()
    ann["Main grid total (GWh)"] = main[years].sum()
    for fuel in ("Hydro", "Coal", "Natural gas", "Diesel"):
        ann[f"{fuel} share of main grid (%)"] = ann[f"{fuel} (GWh)"] / ann["Main grid total (GWh)"] * 100
    ann["Northern grids total (GWh)"] = by_plant[by_plant.Grid == "Northern"][years].sum()
    ann["Stand-alone grids total (GWh)"] = by_plant[by_plant.Grid == "Stand-alone"][years].sum()
    ann["All grids total (GWh)"] = ann["Main grid total (GWh)"] + ann["Northern grids total (GWh)"] + ann["Stand-alone grids total (GWh)"]
    ann.index = pd.to_datetime(ann.index.astype(str) + "-01-01")
    ann.index.name = "date"
    by_plant.columns = [str(c) for c in by_plant.columns]
    return ann, by_plant


def pdf_pages(content, needles):
    import pypdf
    rd = pypdf.PdfReader(io.BytesIO(content))
    keep = []
    for pg in rd.pages:
        try:
            tx = pg.extract_text() or ""
        except Exception:  # noqa: BLE001
            continue
        if any(n in tx for n in needles):
            keep.append(tx)
    return keep


def fetch_sources():
    from curl_cffi import requests as cr
    s = cr.Session()
    out = []
    srcs = list(SOURCES)
    srcs.append((f"ASR{NEXT_YEAR}", BASE + f"Sarawak-Energy-ASR{NEXT_YEAR}.pdf", f"Sarawak Energy Annual and Sustainability Report {NEXT_YEAR}"))
    for label, url, title in srcs:
        try:
            r = s.get(url, impersonate="chrome", timeout=180)
        except Exception as e:  # noqa: BLE001
            print(f"{label}: {type(e).__name__} {str(e)[:100]}", file=sys.stderr)
            continue
        if r.status_code != 200 or r.content[:4] != b"%PDF":
            print(f"{label}: HTTP {r.status_code} (not available)", file=sys.stderr)
            continue
        out.append((label, url, title, len(r.content), r.content))
        print(f"{label}: {len(r.content)} bytes", file=sys.stderr)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--from-text", nargs="*", help="parse saved page-text files instead of downloading (testing)")
    a = ap.parse_args()

    meta = []
    gen = {}
    cap = pd.DataFrame()
    if a.from_text:
        for f in a.from_text:
            pages = split_pages(open(f).read())
            g, t = parse_generation(pages)
            n = check_totals(g, t)
            print(f"{f}: {len(g)} plants, {n} totals checked", file=sys.stderr)
            for p, d in g.items():
                gen.setdefault(p, {}).update(d)
            c = parse_capacity(pages)
            if len(c) > len(cap):
                cap = c
            meta.append((os.path.basename(f), "", "saved text", 0, ""))
    else:
        got = fetch_sources()
        if not got:
            sys.exit("no report could be downloaded")
        for label, url, title, size, content in got:
            pages = pdf_pages(content, ["Net Energy Generated", "Available Capacity"])
            g, t = parse_generation(pages)
            n = check_totals(g, t)
            c = parse_capacity(pages)
            yrs = sorted({y for d in g.values() for y in d})
            print(f"{label}: {len(g)} plants, years {yrs[0]}-{yrs[-1]}, {n} totals checked, {len(c)} capacity rows", file=sys.stderr)
            for p, d in g.items():           # later reports (processed after earlier ones) win on restated years
                gen.setdefault(p, {}).update(d)
            if len(c) >= len(cap) and label != "SEASR2019":
                cap = c
            meta.append((label, url, title, size, f"{yrs[0]}-{yrs[-1]}"))

    ann, by_plant = build_tables(gen)
    src = pd.DataFrame(meta, columns=["Report", "URL", "Title", "PDF size (bytes)", "Years in table"]).set_index("Report")

    notes = [
        "UNITS",
        "GWh = gigawatt-hours of NET energy generated in the calendar year; MW = capacity. By plant tab shows GWh per plant (the reports give MWh).",
        "",
        "COVERAGE",
        "Annual only, from 2015 (2015-2019 from the 2019 report, 2020 onward from the latest report). Sarawak Energy publishes no monthly or daily generation.",
        "Main grid = the company's headline generation mix (e.g. 34,444 GWh in 2024, 75.8% hydro). Northern grids (Lawas / Limbang mini hydro and diesel) and stand-alone diesel systems are small and shown separately.",
        "It is Sarawak Energy's own generation (its plants and subsidiaries listed in the report: Bakun, Murum, Batang Ai, Balingian, Mukah, Sejingkat, PPLS, Sarawak Power Generation, Kidurong, Bintulu, Miri and the diesel and mini-hydro sets); any other producer is not in it.",
        "Exports to West Kalimantan are part of this generation, not subtracted.",
        "",
        "SOURCE",
        "Sarawak Energy Berhad, Annual and Sustainability Reports (net energy generated tables, third-party assured), see the Sources tab for the PDFs.",
        "Each reported 'Total' line is checked against the sum of its plants on every run; the run fails if they differ by more than 0.01% (or 5 MWh).",
        "Capacity is 'available capacity' (net generator output after auxiliary consumption), as listed in the report, not installed capacity; the list covers the plants the report names.",
        "The web pages of sarawakenergy.com time out from GitHub Actions; the PDFs download. If a new report (ASR2025 ...) appears at the same URL pattern it is picked up and its years replace older figures.",
    ]
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    sheets = {"Annual by fuel": ann, "By plant": by_plant}
    if len(cap):
        sheets["Capacity"] = cap.set_index("Plant")
    sheets["Sources"] = src
    xlsx_notes.write_workbook(a.out, sheets, notes, {"UNITS", "COVERAGE", "SOURCE"})
    print(f"Saved {a.out}: {len(by_plant)} plants, years {ann.index.min().year}-{ann.index.max().year}", file=sys.stderr)
    print(ann[["Hydro (GWh)", "Coal (GWh)", "Natural gas (GWh)", "Diesel (GWh)", "Main grid total (GWh)",
               "All grids total (GWh)"]].round(0).astype(int).to_string())


if __name__ == "__main__":
    main()
