"""
Generator (run locally, not in Actions): turns the ID-scan results (discovery_archive/results/china_nbs_audit/idscan_*.tsv)
into asia/china_nbs_archive_ids.py - the NBS releases of Dec 2012 - Oct 2021 that are no longer on the release list but
still online under /sj/zxfb/202302/t20230203_<id>.html - with the title normalised to the form the pull scripts' title
patterns expect (year added from the neighbouring releases where the page title has none).
"""
import glob
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "results", "china_nbs_audit")
rows = {}
for f in glob.glob(os.path.join(RES, "idscan_*.tsv")):
    for line in open(f, encoding="utf-8"):
        p = line.rstrip("\n").split("\t")
        if len(p) >= 3 and not p[1].startswith("ERROR"):
            rows[int(p[0])] = p[1].replace("-国家统计局", "").strip()
ids = sorted(rows)


YEAR_OF = re.compile(r"(\d{4})年\d{1,2}月")   # only monthly / 10-day data releases date their neighbours (annual reports are
                                              # published a year late, e.g. '2014年我国文化...' in Nov 2015)


def year_of(j):
    m = YEAR_OF.search(rows[j])
    return int(m.group(1)) if m else None


def neighbours(i):
    prev = next((y for j in reversed([k for k in ids if k < i][-12:]) if (y := year_of(j))), None)
    nxt = next((y for j in [k for k in ids if k > i][:12] if (y := year_of(j))), None)
    return prev, nxt


def first_month(t):
    m = re.match(r"(?:\d{4}年)?1[-—－](\d{1,2})月", t) or re.match(r"(?:\d{4}年)?(\d{1,2})月", t)
    return int(m.group(1)) if m else None


def year_near(i, t):
    """Year for a title without one: the nearest dated neighbours' year if both agree; at a year boundary the next year for
    a release of months 1-6 and the previous year for months 7-12."""
    prev, nxt = neighbours(i)
    if prev == nxt:
        return prev
    mth = first_month(t)
    if prev and nxt and mth:
        return nxt if mth <= 6 else prev
    return None


TYPES = {
    "industrial": r"规模以上工业增加值",
    "energy": r"能源生产",
    "cpi": r"^\d{4}年\d{1,2}月份居民消费价格|居民消费价格",
    "ppi": r"工业生产者(出厂)?价格",
    "capacity": r"工业产能利用率",
    "profits": r"规模以上工业企业利润",
    "fai": r"全国固定资产投资",
    "retail": r"社会消费品零售总额",
    "prices": r"流通领域重要生产资料",
}
out = {k: [] for k in TYPES}
skipped = []
for i in ids:
    t = rows[i]
    for k, rx in TYPES.items():
        if not re.search(rx, t):
            continue
        if k == "prices":
            m = re.search(r"（(\d{4})年(\d{1,2})月(\d{1,2})日?[-—－](\d{1,2})日?）", t)
            if m:
                day = int(m.group(3))
                xun = "上" if day <= 5 else "中" if day <= 15 else "下"
                t = f"{m.group(1)}年{int(m.group(2))}月{xun}旬流通领域重要生产资料市场价格变动情况"
        if k == "fai" and "民间" in t:
            continue
        if not re.match(r"\d{4}年", t):
            y = year_near(i, t)
            if y is None:
                skipped.append((i, t))
                continue
            t = f"{y}年{t}"
        out[k].append((t, i))
        break
body = ['"""NBS releases of Dec 2012 - Oct 2021 that are online under /sj/zxfb/202302/t20230203_<id>.html but no longer on the',
        'release list (found by the ID scan, discovery_archive/china/CHINA_NBS_AUDIT_PROBE3/5.py; generated by',
        'discovery_archive/china/CHINA_NBS_GEN_IDS.py). Titles are normalised to the pull scripts\' title patterns."""',
        "", "from china_nbs_tables import old_releases", ""]
for k, v in out.items():
    body.append(f"{k.upper()} = old_releases([")
    for t, i in v:
        body.append(f"    ({t!r}, {i}),")
    body.append("])")
    body.append("")
open(os.path.join(HERE, "..", "..", "asia", "china_nbs_archive_ids.py"), "w", encoding="utf-8").write("\n".join(body))
print({k: len(v) for k, v in out.items()}, "skipped (no year):", len(skipped))
for s in skipped[:15]:
    print("  skipped", s)
