"""
Taiwan Power Company (Taipower) open data, two pulls into one workbook
(output/Data and Chart Outputs/taiwan_taipower.xlsx):

  Daily      date x <Fuel>_MWh: net generation by fuel from Taipower's 10-minute unit series (open-data file d006010,
             data.gov.tw dataset 37331 'Electricity generated by each unit in the past'): sum of NET_P (MW) x 10/60 h
             over all units of a fuel, one row per day with all 144 ten-minute stamps. Taipower replaces the file once a
             month with a rolling three-month window that ends about three months back (the window on 10 Oct 2026 was
             1 Mar - 31 May 2026), so history can only be built up from the first run on: each run adds the days of the
             current window that are not stored yet. Pumped-storage and battery net output (negative when pumping or
             charging) are kept in their own columns, not folded into any fuel.
  Peak       date x supply capacity / peak load / reserve (GW, %) and industrial / residential electricity use
             (GWh) from Taipower's 'past supply and demand' file (d006005, data.gov.tw dataset 19995): the previous and
             the current year up to last month; stored days are kept and the file's days replace them.
  Units      notes, units, fuel mapping, days skipped.

Taipower's own page (www.taipower.com.tw) answers 403 from GitHub Actions; service.taipower.com.tw/data/opendata/ works.

    python3 taiwan/TAIWAN_TAIPOWER.py --out "output/Data and Chart Outputs/taiwan_taipower.xlsx"
"""
import argparse
import io
import os
import re
import sys
from collections import defaultdict

import pandas as pd
import requests

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import xlsx_notes  # noqa: E402

BASE = "https://service.taipower.com.tw/data/opendata/apply/file/"
UNITS_URL = BASE + "d006010/001.json"
PEAK_URL = BASE + "d006005/001.csv"
UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36"}
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output",
                           "Data and Chart Outputs", "taiwan_taipower.xlsx")
REC = re.compile(r'\{"FUEL_TYPE":"([^"]*)","UNIT_NAME":"([^"]*)","DATETIME":"([^"]*)","NET_P":"([^"]*)"\}')
# first match wins; Taipower's FUEL_TYPE labels (Chinese) -> chart fuel
FUEL_RULES = [("抽蓄", "Pumped_storage"), ("抽水", "Pumped_storage"), ("儲能", "Battery_storage"), ("核", "Nuclear"),
              ("煤", "Coal"), ("燃氣", "Gas"), ("天然氣", "Gas"), ("LNG", "Gas"), ("氣", "Gas"), ("油", "Oil"),
              ("水力", "Hydro"), ("風", "Wind"), ("太陽", "Solar"), ("生質", "Bioenergy"), ("地熱", "Other"),
              ("汽電", "Cogeneration"), ("共生", "Cogeneration"), ("再生", "Other")]
STAMPS = 144


def fuel_of(label):
    for key, f in FUEL_RULES:
        if key in label:
            return f
    return "Other"


def get(url, **kw):
    last = None
    for i in range(3):
        try:
            r = requests.get(url, headers=UA, timeout=(15, 300), **kw)
            r.raise_for_status()
            return r
        except requests.RequestException as e:
            last = e
            print(f"  attempt {i + 1}/3 {url}: {type(e).__name__}", file=sys.stderr)
    raise last


def units_window():
    """START_DATE / END_DATE of the current 10-minute file, from its first bytes."""
    r = requests.get(UNITS_URL, headers=UA, timeout=(15, 120), stream=True)
    r.raise_for_status()
    head = next(r.iter_content(600), b"").decode("utf-8-sig", "replace")
    r.close()
    s, e = re.search(r'"START_DATE":"([^"]+)"', head), re.search(r'"END_DATE":"([^"]+)"', head)
    return (pd.Timestamp(s.group(1)), pd.Timestamp(e.group(1))) if s and e else (None, None)


def pull_units(have_until):
    """Stream the 10-minute file; returns (daily MWh frame, label map, skipped-day notes) or None if nothing new."""
    start, end = units_window()
    print(f"  10-minute file window {start} .. {end}; stored days to {have_until}")
    if end is None:
        raise RuntimeError("could not read the window of the 10-minute file")
    if have_until is not None and end.normalize() <= have_until:
        print("  nothing new in the 10-minute file")
        return None
    mwh = defaultdict(float)
    stamps = defaultdict(set)
    blanks = defaultdict(int)
    labels = {}
    r = requests.get(UNITS_URL, headers=UA, timeout=(15, 600), stream=True)
    r.raise_for_status()
    buf = ""
    n = 0
    for chunk in r.iter_content(8 * 1024 * 1024, decode_unicode=False):
        buf += chunk.decode("utf-8", "ignore")
        last = buf.rfind("}")
        part, buf = buf[:last + 1], buf[last + 1:]
        for lab, unit, dt, v in REC.findall(part):
            n += 1
            day = dt[:10]
            fuel = labels.setdefault(lab, fuel_of(lab))
            stamps[day].add(dt)
            if v.strip() in ("", "-", "NaN"):
                blanks[day] += 1
                continue
            mwh[(day, fuel)] += float(v) * 10.0 / 60.0
    print(f"  parsed {n} unit records, {len(stamps)} days, labels {labels}")
    if n == 0:
        raise RuntimeError("no unit records parsed from the 10-minute file")
    rows, skipped = {}, []
    for day, st in stamps.items():
        if len(st) < STAMPS:
            skipped.append(f"{day} ({len(st)} of {STAMPS} stamps)")
            continue
        rows[pd.Timestamp(day)] = {f"{f}_MWh": mwh[(d, f)] for (d, f) in list(mwh) if d == day}
    df = pd.DataFrame.from_dict(rows, orient="index").sort_index()
    df.index.name = "date"
    return df, labels, skipped, sum(blanks.values())


def pull_peak():
    r = get(PEAK_URL)
    df = pd.read_csv(io.StringIO(r.content.decode("utf-8-sig")))
    df["date"] = pd.to_datetime(df["日期"].astype(str), format="%Y%m%d")
    df = df.set_index("date").sort_index()
    out = pd.DataFrame({
        "Net_peak_supply_capacity_GW": df["淨尖峰供電能力(萬瓩)"] / 100.0,
        "Peak_load_GW": df["尖峰負載(萬瓩)"] / 100.0,
        "Reserve_capacity_GW": df["備轉容量(萬瓩)"] / 100.0,
        "Reserve_margin_pct": df["備轉容量率(%)"],
        "Industrial_use_GWh": df["工業用電(百萬度)"],
        "Residential_use_GWh": df["民生用電(百萬度)"]})
    return out


def read_old(path, sheet):
    if not os.path.exists(path):
        return None
    try:
        d = pd.read_excel(path, sheet_name=sheet, index_col=0)
        d.index = pd.to_datetime(d.index)
        return d
    except Exception as e:  # noqa: BLE001
        print(f"  stored sheet {sheet} unreadable ({type(e).__name__}); starting it again", file=sys.stderr)
        return None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()
    old_daily, old_peak = read_old(args.out, "Daily"), read_old(args.out, "Peak")

    daily, labels, skipped, nblank = old_daily, {}, [], 0
    try:
        res = pull_units(old_daily.index.max() if old_daily is not None and len(old_daily) else None)
        if res:
            new, labels, skipped, nblank = res
            daily = new if old_daily is None else pd.concat([old_daily[~old_daily.index.isin(new.index)], new]).sort_index()
    except Exception as e:  # noqa: BLE001
        if old_daily is None:
            print(f"  10-minute unit file failed and nothing stored: {type(e).__name__}: {e}", file=sys.stderr)
        else:
            print(f"  10-minute unit file failed ({type(e).__name__}: {e}); keeping stored days", file=sys.stderr)
    peak = old_peak
    try:
        new = pull_peak()
        peak = new if old_peak is None else pd.concat([old_peak[~old_peak.index.isin(new.index)], new]).sort_index()
    except Exception as e:  # noqa: BLE001
        print(f"  peak file failed ({type(e).__name__}: {e}); keeping stored days", file=sys.stderr)
    sheets = {}
    if daily is not None and len(daily):
        d = daily.copy()
        d["Total_MWh"] = d[[c for c in d.columns if c.endswith("_MWh") and c not in
                            ("Pumped_storage_MWh", "Battery_storage_MWh", "Total_MWh")]].sum(axis=1, min_count=1)
        sheets["Daily"] = d.round(1)
    if peak is not None and len(peak):
        sheets["Peak"] = peak.round(3)
    if not sheets:
        raise SystemExit("nothing pulled and nothing stored")
    notes = list(NOTES)
    if labels:
        notes += ["", "FUEL MAPPING (Taipower FUEL_TYPE label -> column)"] + [f"{k} -> {v}" for k, v in sorted(labels.items())]
    if skipped:
        notes += ["", "DAYS SKIPPED in the last run (fewer than 144 ten-minute stamps): " + "; ".join(skipped[:40])]
    if nblank:
        notes.append(f"Blank NET_P readings in the last run (counted as no reading, not as zero): {nblank}")
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    xlsx_notes.write_workbook(args.out, sheets, notes, {"UNITS", "SOURCE", "UPDATES", "FUEL MAPPING (Taipower FUEL_TYPE label -> column)"})
    for k, v in sheets.items():
        print(f"  {k}: {len(v)} rows {v.index.min():%Y-%m-%d}..{v.index.max():%Y-%m-%d}")


NOTES = [
    "UNITS",
    "Daily: MWh per day = sum over units of net power (MW) x 10/60 h, by fuel. Pumped_storage and Battery_storage are net "
    "output (negative while pumping or charging). Total_MWh = fuels excluding pumped storage and batteries.",
    "Peak: GW (peak supply capacity, peak load, reserve capacity), % (reserve margin), GWh per day (industrial and residential "
    "use as reported by Taipower, 'million kWh').",
    "",
    "SOURCE",
    "Taiwan Power Company open data (service.taipower.com.tw/data/opendata/): d006010 'Electricity generated by each unit in the "
    "past' (data.gov.tw 37331, EMS data, 10-minute net generation, updated monthly with a three-month lag, rolling three-month "
    "window); d006005 'past electricity supply and demand' (data.gov.tw 19995, daily, previous and current year to last month). "
    "Taipower notes that EMS data can differ slightly from its official figures.",
    "",
    "UPDATES",
    "Incremental: the committed workbook is the history store. The 10-minute file is downloaded (about 200 MB) only when its "
    "window ends after the last stored day; days with all 144 stamps are added. History starts with the first window "
    "available at the first run.",
]

if __name__ == "__main__":
    main()
