"""
Taiwan generation by fuel, rolled up from 10-minute data to DAILY and MONTHLY series
(output/Data and Chart Outputs/taiwan_generation_rollup.xlsx). Two separate series, never mixed in one table:

  Daily Zenodo / Monthly Zenodo
      Taipower's 'Electricity generated by each unit in the past' (data.gov.tw 37331) as published on Zenodo
      (doi 10.5281/zenodo.7537890, Fu and Chen, licence CC BY 4.0; underlying data under Taiwan's Open Government Data
      License v1.0): 10-minute MW by type, Jan 2017 - 1 Jul 2022, Taipower's EMS units PLUS the independent power
      producers (ippLng, ippCoal) and cogeneration. Downloaded once (checksum verified) and rolled up; the stored sheets
      are the history after that. Not a Taipower or government publication in this form: a third-party copy.
  Daily EMS / Monthly EMS
      The same dataset's current files from Taipower (service.taipower.com.tw .../d006010/001.json: a rolling
      three-month window, replaced monthly, ending about three months back) and the older windows that the Internet
      Archive (web.archive.org) holds copies of. EMS-dispatched Taipower units ONLY: no IPPs, almost no solar or wind
      (about half of national generation). Each window is ingested once (sheet 'Windows'); a window that the archive
      copy truncated (no closing brackets) is recorded as failed and not used.
  Coverage
      Each series against the Energy Administration's national generation by fuel (E-STAT, taiwan_esist_monthly.xlsx),
      annual for Zenodo years and monthly for EMS months, for periods with >= 90% of 10-minute intervals.

Roll-up rules (no scaling, no filling): DAILY = sum over present 10-minute intervals of MW x 10/60 h (MWh) by fuel, the
number of distinct 10-minute stamps present (n_intervals, 144 = full day) and the average GW over the PRESENT intervals;
a day with fewer than 130 of 144 intervals (< 90%) is flagged (complete = 0) and left out of charts. MONTHLY = the same
sums over the month, coverage_pct = intervals present / (days x 144); charted only when >= 90%. Duplicate (unit, stamp)
records are counted once; Zenodo readings stamped off the 10-minute grid (335 of 280,625, mostly 2017) are put in the slot they
fall in and only the first reading of a slot is kept. Pumped storage is generation only (E-STAT also counts pumped-storage output in its total).

    python3 taiwan/TAIWAN_GEN_ROLLUP.py --out "output/Data and Chart Outputs/taiwan_generation_rollup.xlsx"
"""
import argparse
import calendar
import hashlib
import io
import json
import os
import re
import sys
import time
from collections import defaultdict

import pandas as pd
import requests

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
sys.path.insert(0, HERE)
import xlsx_notes  # noqa: E402
from TAIWAN_TAIPOWER import FUEL_RULES, REC, UA, UNITS_URL, fuel_of  # noqa: E402

DATA = os.path.join(ROOT, "output", "Data and Chart Outputs")
DEFAULT_OUT = os.path.join(DATA, "taiwan_generation_rollup.xlsx")
ESIST = os.path.join(DATA, "taiwan_esist_monthly.xlsx")
ZENODO_API = "https://zenodo.org/api/records/7537890"
ZENODO_FILE = "powerRatio_10min_2017Jan_2022Jun.csv"
STAMPS = 144
MIN_SHARE = 0.9
MIN_STAMPS = int(STAMPS * MIN_SHARE)   # 129.6 -> 129; "< 90%" means fewer than 130
FUELS = ["Hydro", "Gas", "Wind", "Solar", "Coal", "Nuclear", "Oil", "Cogeneration", "Pumped_storage", "Other"]
# Zenodo column -> fuel (ippLng / ippCoal / diesel also kept as 'of which' memo columns)
ZEN_MAP = {"hydro": "Hydro", "solar": "Solar", "wind": "Wind", "nuclear": "Nuclear", "coal": "Coal", "ippCoal": "Coal",
           "lng": "Gas", "ippLng": "Gas", "oil": "Oil", "diesel": "Oil", "coGen": "Cogeneration", "pumpGen": "Pumped_storage"}
ZEN_MEMO = {"ippCoal": "Coal_of_which_IPP", "ippLng": "Gas_of_which_IPP", "diesel": "Oil_of_which_diesel"}
ESTAT = {"Hydro": "Renewable Energy - Hydro", "Solar": "Renewable Energy - Solar PV", "Wind": "Renewable Energy - Wind",
         "Nuclear": "Nuclear", "Coal": "Thermal - Coal-Fired", "Gas": "Thermal - LNG-Fired", "Oil": "Thermal - Oil-Fired",
         "Pumped_storage": "Pumped Storage", "Total": "Grand Total"}


def log(*a):
    print(*a, flush=True)


# ---------------------------------------------------------------- roll-up helpers
def finish_daily(rows, memo=()):
    """rows: {date: {'n': intervals, '<Fuel>_MWh': x, ...}} -> daily frame with GW columns and flags."""
    d = pd.DataFrame.from_dict(rows, orient="index").sort_index()
    d.index = pd.to_datetime(d.index)
    d.index.name = "date"
    fuels = [f for f in FUELS if f"{f}_MWh" in d.columns]
    d["Total_MWh"] = d[[f"{f}_MWh" for f in fuels]].sum(axis=1, min_count=1)
    hours = d["n_intervals"] / 6.0
    for f in fuels + ["Total"]:
        d[f"{f}_GW"] = d[f"{f}_MWh"] / hours / 1000.0
    d["complete"] = (d["n_intervals"] >= MIN_STAMPS + 1).astype(int)
    cols = (["n_intervals", "complete"] + [f"{f}_MWh" for f in fuels] + ["Total_MWh"] + [f"{f}_GW" for f in fuels] + ["Total_GW"]
            + [c for c in d.columns if c in memo] + [c for c in d.columns if c in ("units_reporting", "source")])
    out = d[[c for c in cols if c in d.columns]].copy()
    for c in out.columns:
        if c.endswith("_MWh"):
            out[c] = out[c].round(1)
        elif c.endswith("_GW"):
            out[c] = out[c].round(4)
    return out


def monthly_from_daily(d):
    fuels = [c[:-4] for c in d.columns if c.endswith("_MWh") and c != "Total_MWh" and "_of_which_" not in c]
    mw = [f"{f}_MWh" for f in fuels] + ["Total_MWh"]
    m = d[["n_intervals"] + mw + [c for c in d.columns if "_of_which_" in c and c.endswith("_MWh")]].resample("MS").sum(min_count=1)
    m = m[m["n_intervals"].notna() & (m["n_intervals"] > 0)]
    m["days_present"] = d["n_intervals"].gt(0).resample("MS").sum().reindex(m.index)
    m["coverage_pct"] = m["n_intervals"] / (m.index.days_in_month * STAMPS) * 100.0
    hours = m["n_intervals"] / 6.0
    for f in fuels + ["Total"]:
        m[f"{f}_GW"] = m[f"{f}_MWh"] / hours / 1000.0
    m["charted"] = (m["coverage_pct"] >= MIN_SHARE * 100).astype(int)
    cols = (["n_intervals", "days_present", "coverage_pct", "charted"] + [f"{f}_MWh" for f in fuels] + ["Total_MWh"]
            + [f"{f}_GW" for f in fuels] + ["Total_GW"] + [c for c in m.columns if "_of_which_" in c])
    out = m[cols].copy()
    for c in out.columns:
        if c.endswith("_MWh"):
            out[c] = out[c].round(1)
        elif c.endswith("_GW"):
            out[c] = out[c].round(4)
    out["coverage_pct"] = out["coverage_pct"].round(2)
    out.index.name = "month"
    return out


def read_sheet(path, name):
    if not os.path.exists(path):
        return None
    try:
        d = pd.read_excel(path, sheet_name=name, index_col=0)
        if name.startswith(("Daily", "Monthly")):
            d.index = pd.to_datetime(d.index)
        return d
    except Exception as e:  # noqa: BLE001
        log(f"  stored sheet {name} not readable ({type(e).__name__}); starting it again")
        return None


# ---------------------------------------------------------------- Zenodo
def zenodo_daily():
    meta = requests.get(ZENODO_API, headers=UA, timeout=60).json()
    f = next(x for x in meta["files"] if x["key"] == ZENODO_FILE)
    url, want = f["links"]["self"], f.get("checksum", "")
    r = requests.get(url, headers=UA, timeout=(20, 300))
    r.raise_for_status()
    md5 = hashlib.md5(r.content).hexdigest()
    ok = want.endswith(md5) if want else None
    log(f"  Zenodo {ZENODO_FILE}: {len(r.content)} bytes, md5 {md5}, record checksum {want}, match {ok}")
    if ok is False:
        raise RuntimeError("Zenodo checksum mismatch")
    z = pd.read_csv(io.BytesIO(r.content), parse_dates=["datetime"], index_col="datetime")
    rows_in = len(z)
    off = int(((z.index.minute % 10 != 0) | (z.index.second != 0)).sum())
    z.index = z.index.floor("10min")          # a reading stamped off the 10-minute grid belongs to the slot it falls in
    z = z[~z.index.duplicated(keep="first")]  # two readings in one slot: the first is kept
    z = z.sort_index()
    info = {"title": meta["metadata"].get("title"), "doi": meta.get("doi"), "licence": (meta["metadata"].get("license") or {}).get("id"),
            "md5": md5, "rows_in_file": rows_in, "rows_off_the_10min_grid": off, "rows_after_slotting": len(z), "first": str(z.index.min()), "last": str(z.index.max()), "modified": meta.get("modified")}
    fx = pd.DataFrame(index=z.index)
    for fuel in sorted(set(ZEN_MAP.values())):
        cols = [c for c, v in ZEN_MAP.items() if v == fuel and c in z.columns]
        fx[fuel] = z[cols].sum(axis=1, min_count=1)
    memo = pd.DataFrame({ZEN_MEMO[c] : z[c] for c in ZEN_MEMO if c in z.columns})
    day = fx.index.normalize()
    g = (fx * (10.0 / 60.0)).groupby(day).sum(min_count=1)
    g.columns = [f"{c}_MWh" for c in g.columns]
    gm = (memo * (10.0 / 60.0)).groupby(day).sum(min_count=1)
    gm.columns = [f"{c}_MWh" for c in gm.columns]
    d = g.join(gm)
    d.insert(0, "n_intervals", fx.groupby(day).size())
    d["source"] = "Zenodo 7537890"
    rows = d.drop(columns="source").to_dict(orient="index")
    out = finish_daily(rows, memo=tuple(gm.columns))
    out["source"] = "Zenodo 7537890"
    return out, info


# ---------------------------------------------------------------- Taipower d006010 (official and Internet Archive copies)
def window_of(url):
    r = requests.get(url, headers=UA, timeout=(20, 180), stream=True)
    r.raise_for_status()
    head = next(r.iter_content(700), b"").decode("utf-8-sig", "replace")
    r.close()
    s, e = re.search(r'"START_DATE":"([^"]+)"', head), re.search(r'"END_DATE":"([^"]+)"', head)
    return (pd.Timestamp(s.group(1)), pd.Timestamp(e.group(1))) if s and e else (None, None)


def stream_window(url, label):
    """Stream one d006010 file -> (daily frame, notes dict). Raises if the file is cut short."""
    mwh = defaultdict(float)
    stamps = defaultdict(set)
    units = defaultdict(set)
    recs = defaultdict(int)
    seen = set()
    dup = blank = n = 0
    r = requests.get(url, headers=UA, timeout=(20, 900), stream=True)
    r.raise_for_status()
    buf, tail = "", ""
    for chunk in r.iter_content(8 * 1024 * 1024):
        text = chunk.decode("utf-8", "ignore")
        tail = (tail + text)[-40:]
        buf += text
        k = buf.rfind("}")
        part, buf = buf[:k + 1], buf[k + 1:]
        for lab, unit, dt, v in REC.findall(part):
            n += 1
            key = hash((lab, unit, dt))
            if key in seen:
                dup += 1
                continue
            seen.add(key)
            day = dt[:10]
            stamps[day].add(dt)
            units[day].add(unit)
            recs[day] += 1
            if v.strip() in ("", "-", "NaN"):
                blank += 1
                continue
            mwh[(day, fuel_of(lab))] += float(v) * 10.0 / 60.0
    complete = tail.rstrip().endswith("]}}")
    log(f"  {label}: {n} records ({dup} duplicates, {blank} blank), {len(stamps)} days, closing brackets present: {complete}")
    if n == 0 or not complete:
        raise RuntimeError(f"file incomplete or empty (records {n}, closing brackets {complete})")
    rows = {}
    for day, st in stamps.items():
        row = {"n_intervals": len(st), "units_reporting": len(units[day])}
        for (dd, f), v in mwh.items():
            if dd == day:
                row[f"{f}_MWh"] = v
        rows[day] = row
    return finish_daily(rows), {"records": n, "duplicates": dup, "blank": blank}


def archive_captures():
    """Distinct captures of the d006010 file held by the Internet Archive: [(timestamp, digest)]."""
    u = ("http://web.archive.org/cdx/search/cdx?url=service.taipower.com.tw/data/opendata/apply/file/d006010/001.json"
         "&output=json&filter=statuscode:200")
    for i in range(4):
        try:
            r = requests.get(u, headers=UA, timeout=60)
            if r.status_code == 200 and r.text.strip():
                rows = json.loads(r.text)[1:]
                seen, out = set(), []
                for row in rows:
                    if row[5] not in seen:
                        seen.add(row[5])
                        out.append((row[1], row[5]))
                return out
        except Exception as e:  # noqa: BLE001
            log(f"  CDX attempt {i + 1}: {type(e).__name__}")
        time.sleep(8 * (i + 1))
    return []


def ems_pull(windows, daily):
    """Add the windows not ingested yet. windows: DataFrame of ingested/failed windows. Returns (daily, windows, log lines)."""
    lines = []
    rows = [] if windows is None else windows.to_dict("records")
    have = {(str(r["window_start"])[:10], str(r["window_end"])[:10]) for r in rows if r["status"] == "ok"}
    failed = {str(r.get("capture")) for r in rows if r["status"] != "ok" and str(r.get("capture")) not in ("", "nan", "official")}

    def ingest(url, label, capture, source):
        nonlocal daily
        s, e = window_of(url)
        if s is None:
            raise RuntimeError("no START_DATE/END_DATE in the file head")
        if (str(s)[:10], str(e)[:10]) in have and capture != "official":
            lines.append(f"{label}: window {s:%Y-%m-%d}..{e:%Y-%m-%d} already stored")
            return
        if capture == "official" and (str(s)[:10], str(e)[:10]) in have:
            lines.append(f"{label}: official window {s:%Y-%m-%d}..{e:%Y-%m-%d} already stored")
            return
        d, st = stream_window(url, label)
        d["source"] = source
        daily = d if daily is None else pd.concat([daily[~daily.index.isin(d.index)], d]).sort_index()
        have.add((str(s)[:10], str(e)[:10]))
        rows.append({"window_start": s, "window_end": e, "source": source, "capture": capture, "days": len(d),
                     "days_complete": int(d["complete"].sum()), "records": st["records"], "duplicates": st["duplicates"],
                     "status": "ok", "note": "", "run_date": pd.Timestamp.utcnow().strftime("%Y-%m-%d")})
        lines.append(f"{label}: ingested {s:%Y-%m-%d}..{e:%Y-%m-%d}, {len(d)} days ({int(d['complete'].sum())} complete)")

    for ts, dig in archive_captures():
        if ts in failed:
            continue
        url = f"https://web.archive.org/web/{ts}id_/https://service.taipower.com.tw/data/opendata/apply/file/d006010/001.json"
        try:
            ingest(url, f"Internet Archive capture {ts}", ts, f"Internet Archive copy of Taipower d006010, capture {ts}")
        except Exception as e:  # noqa: BLE001
            msg = f"{type(e).__name__}: {str(e)[:150]}"
            log(f"  archive capture {ts} not used: {msg}")
            lines.append(f"Internet Archive capture {ts} NOT used: {msg}")
            rows.append({"window_start": pd.NaT, "window_end": pd.NaT, "source": "Internet Archive", "capture": ts, "days": 0,
                         "days_complete": 0, "records": 0, "duplicates": 0, "status": "failed", "note": msg,
                         "run_date": pd.Timestamp.utcnow().strftime("%Y-%m-%d")})
    try:
        ingest(UNITS_URL, "Taipower file", "official", "Taipower d006010 (service.taipower.com.tw)")
    except Exception as e:  # noqa: BLE001
        log(f"  Taipower file failed: {type(e).__name__}: {e}")
        lines.append(f"Taipower file failed in the last run: {type(e).__name__}: {str(e)[:150]}")
    w = pd.DataFrame(rows)
    return daily, w, lines


# ---------------------------------------------------------------- coverage against E-STAT
def estat(sheet):
    try:
        d = pd.read_excel(ESIST, sheet_name=sheet, index_col=0)
    except Exception:  # noqa: BLE001
        return None
    d.index = pd.to_datetime(d.index) if sheet.endswith("M") else pd.to_datetime(d.index.astype(int).astype(str), format="%Y")
    return d


def coverage(label, monthly):
    """Rows comparing a monthly roll-up with E-STAT (annual for years of >= 90% coverage, monthly where E-STAT has the month)."""
    out = []
    if monthly is None or monthly.empty:
        return out
    fuels = [c[:-3] for c in monthly.columns if c.endswith("_GW")]
    ea, em = estat("GEN A"), estat("GEN M")
    yr = monthly.groupby(monthly.index.year)
    if ea is not None:
        for y, g in yr:
            exp = sum(calendar.monthrange(y, m)[1] for m in range(1, 13)) * STAMPS
            share = g["n_intervals"].sum() / exp
            t = pd.Timestamp(year=y, month=1, day=1)
            if t not in ea.index:
                continue
            hrs = (366 if calendar.isleap(y) else 365) * 24
            for f in fuels:
                col = ESTAT.get(f, ESTAT["Total"] if f == "Total" else None)
                avg = g[f"{f}_MWh"].sum() / (g["n_intervals"].sum() / 6.0) / 1000.0
                es = ea.loc[t, col] / hrs if col in ea.columns else float("nan")
                out.append([label, "year", str(y), round(share * 100, 1), f, round(avg, 3), round(es, 3) if es == es else None,
                            round(avg / es * 100, 1) if es == es and es else None, "yes" if share >= MIN_SHARE else "no (< 90% of intervals)"])
    if em is not None:
        for t, row in monthly.iterrows():
            if t not in em.index:
                continue
            hrs = t.days_in_month * 24
            for f in fuels:
                col = ESTAT.get(f, ESTAT["Total"] if f == "Total" else None)
                es = em.loc[t, col] / hrs if col in em.columns else float("nan")
                out.append([label, "month", f"{t:%Y-%m}", row["coverage_pct"], f, round(row[f"{f}_GW"], 3),
                            round(es, 3) if es == es else None, round(row[f"{f}_GW"] / es * 100, 1) if es == es and es else None,
                            "yes" if row["coverage_pct"] >= MIN_SHARE * 100 else "no (< 90% of intervals)"])
    return out


COV_COLS = ["series", "period_type", "period", "intervals_pct", "fuel", "series_avg_GW", "E-STAT_avg_GW", "series_as_pct_of_E-STAT", "comparable"]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--skip-ems", action="store_true")
    args = ap.parse_args()
    out = args.out
    zd, ed = read_sheet(out, "Daily Zenodo"), read_sheet(out, "Daily EMS")
    win = read_sheet(out, "Windows")
    if win is not None:
        win = win.reset_index()
        win = win.rename(columns={win.columns[0]: "window_start"})
    zen_info = None
    if zd is None:
        zd, zen_info = zenodo_daily()
    elif os.path.exists(out):
        try:
            zen_info = json.loads(pd.read_excel(out, sheet_name="Units", header=None).iloc[:, 0].astype(str)
                                  .str.extract(r"^ZENODO_INFO (.*)$").dropna().iloc[0, 0])
        except Exception:  # noqa: BLE001
            zen_info = None
    lines = []
    if not args.skip_ems:
        ed, win, lines = ems_pull(win, ed)
    sheets = {}
    mz = monthly_from_daily(zd)
    sheets["Daily Zenodo"], sheets["Monthly Zenodo"] = zd, mz
    cov = coverage("Zenodo (Taipower EMS units + IPPs, third-party copy)", mz)
    if ed is not None and len(ed):
        me = monthly_from_daily(ed.drop(columns=[c for c in ("source",) if c in ed.columns]))
        sheets["Daily EMS"], sheets["Monthly EMS"] = ed, me
        cov += coverage("Taipower EMS units (d006010)", me)
    if win is not None and len(win):
        w = win.copy()
        sheets["Windows"] = w.set_index("window_start") if "window_start" in w.columns else w
    sheets["Coverage"] = pd.DataFrame(cov, columns=COV_COLS).set_index("series")
    notes = list(NOTES)
    if zen_info:
        notes += ["", "SERIES 1 - ZENODO", f"ZENODO_INFO {json.dumps(zen_info)}"]
        notes += [f"{k}: {v}" for k, v in zen_info.items()]
    if lines:
        notes += ["", "LAST RUN (Taipower d006010 windows)"] + lines
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    xlsx_notes.write_workbook(out, sheets, notes, {"UNITS", "SOURCES AND LICENCE", "ROLL-UP RULES", "COVERAGE", "SERIES 1 - ZENODO",
                                                   "LAST RUN (Taipower d006010 windows)"})
    for k, v in sheets.items():
        print(f"  {k}: {len(v)} rows")


NOTES = [
    "UNITS",
    "MWh = megawatt-hours (sum of 10-minute MW x 10/60 h over the intervals present); GW = average power in gigawatts over the "
    "intervals present (MWh / hours present / 1000); n_intervals = distinct 10-minute stamps present (144 = full day); "
    "complete = 1 when >= 90% of the day's intervals are present; coverage_pct = intervals present / intervals in the month; "
    "charted = 1 when coverage_pct >= 90. Nothing is scaled up or filled: a short day or month is reported as it is and left "
    "out of the charts.",
    "",
    "SOURCES AND LICENCE",
    "Zenodo 'Taiwan electricity generation and demand data, 2017 January - 2022 July' (Chun Fu, Barton Chen; doi "
    "10.5281/zenodo.7537890; licence CC BY 4.0; file powerRatio_10min_2017Jan_2022Jun.csv), built by its authors from Taipower's "
    "data.gov.tw 37331 file; the data are Taiwan Open Government Data License v1.0. It lists 'both the generation from Taipower "
    "company and IPP (independent power plant)'; lng = gas, coGen = cogeneration. Its 10-minute series has gaps (stamps missing "
    "on 2019-06 for 57 days, and short holes in other years): see n_intervals. It ends 1 Jul 2022; there is no overlapping period "
    "with the current Taipower file, so it was checked against E-STAT annual national generation instead (sheet Coverage).",
    "Taipower d006010 'Electricity generated by each unit in the past' (service.taipower.com.tw/data/opendata/apply/file/d006010/"
    "001.json; data.gov.tw 37331; Open Government Data License v1.0): EMS data, 10-minute net MW per Taipower-dispatched unit, "
    "updated monthly with three-month-old data (rolling three-month window). Taipower notes EMS data can differ slightly from its "
    "official figures. Older windows come from the Internet Archive's copies of the same URL where the copy is complete.",
    "Energy Administration E-STAT (taiwan_esist_monthly.xlsx) is the national total used only for the Coverage sheet.",
    "",
    "ROLL-UP RULES",
    "Fuel from Taipower's FUEL_TYPE label (TAIWAN_TAIPOWER.FUEL_RULES): gas, coal, oil (fuel oil + diesel/light oil), cogeneration, "
    "hydro, wind, solar, nuclear, pumped storage (generation only). The Zenodo columns map lng + ippLng = Gas, coal + ippCoal = Coal, "
    "oil + diesel = Oil; the IPP and diesel parts are kept as 'of which' columns. Total = all fuels listed (pumped-storage "
    "generation included, as in E-STAT). EMS covers dispatched Taipower units only (no IPPs; rooftop and most wind and solar are "
    "outside it) so its fuel shares are NOT national shares; Zenodo covers EMS units plus IPPs and cogeneration, still not "
    "self-generation, rooftop solar or small renewables.",
    "",
    "COVERAGE",
    "See the sheet Coverage: series average GW against E-STAT national average GW for the same year or month (periods with >= 90% "
    "of intervals are marked comparable). Shares below 100% show what each source leaves out; nothing is added to close them.",
]

if __name__ == "__main__":
    main()
